name: deploy-service
# on – определяет события, которые запускают воркфлоу
on:
  push:
    branches: [ "main" ]
    paths:
      - 'service/**'
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - run: echo "start steps deploy-service"
      - run: ls
      - run: echo "end steps deploy-service"